# jekyll serve
title: Rails4Business
description: "Fai nascere i tuoi progetti con Ruby on Rails"
theme: just-the-docs

logo: "/assets/images/rails4business.png"
favicon_ico: "/assets/images/rails4business.png"

url: "https://rails4b.com"
baseurl: ""            # GitHub Pages custom domain: lascia vuoto
permalink: pretty

nav_sort: case_sensitive
enable_copy_code_button: true
heading_anchors: true

search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-github-metadata

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# --- COLLECTIONS ---
collections:
  flowpulse:
    output: true
    permalink: "/flowpulse/:path/"
  markpostura:
    output: true
    permalink: "/markpostura/:path/"
  weeks:
    output: true
    permalink: "/weeks/:name/"
  routines:
    output: true
    permalink: "/routines/:path/"
  rails:
    output: true
    permalink: "/rails/:path/"


just_the_docs:
  collections:
    flowpulse:
      name: Flowpulse
      nav_fold: true
    markpostura:
      name: MarkPostura
      nav_fold: true
    weeks:
      name: Settimane
      nav_fold: true
    routines:
      name: Routine
      nav_fold: true
    rails:
      name: Rails Notes
      nav_fold: true
   

# Default front matter per collezioni (layout + ordine nav)
defaults:
  - scope: { path: "", type: "flowpulse" }
    values: { layout: "default", nav_order: 10 }
  - scope: { path: "", type: "markpostura" }
    values: { layout: "default", nav_order: 20 }
  - scope: { path: "", type: "weeks" }
    values: { layout: "default", nav_order: 30 }
  - scope: { path: "", type: "routines" }
    values: { layout: "default", nav_order: 40 }
  - scope: { path: "", type: "rails" }
    values: { layout: "default", nav_order: 50 }


aux_links:
  Template Repository: https://github.com/marcobeffa/rails4b
aux_links_new_tab: false
